# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Michael"
description:        "Something about writing/product/coding/architect"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//crazylang.github.io"
author:             "Michael"
twitter:
  username:         "Michael"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "//crazylang.github.io/about"
  - name:           "project"
    href:           "//github.com/CrazyLang/CrazyLang.github.io"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
